accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from accounts.forms import LoginForm
from accounts.views import profile, profile_edit, signup, PasswordsChangeView

app_name = 'accounts'

# app_name을 넣으면 무조건 reserve('accounts:profile')이런식으로 url을 만들어야한다
# url 'profile'이렇게 쓰고 싶으면 app_name이 없고 name만 설정해야한다!

urlpatterns = [
    # 로그인 되어있는데 로그인페이지로 임의로 들어가면 redirect_authenticated_user =True로 해준다, 그리고 setting가서 설정!
    path('login/', LoginView.as_view(template_name='accounts/login_form.html', form_class=LoginForm, redirect_authenticated_user =True), name='login'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', profile_edit, name='profile_edit'),
    # path('profile/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/change-password.html', success_url=reverse_lazy('accounts:profile')), name='password'),
    # path('profile/update/', account_update, name='account_update'),
    path('profile/password/', PasswordsChangeView.as_view(template_name='accounts/change-password.html'), name='password'),
    path('signup/', signup, name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

askcompany/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# 아래 두개처럼 쓰면 안됨
# from django.conf import global_settings
# from askcompany import settings
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='root.html'), name='root'),

    # path('', RedirectView.as_view(url='/instagram/'), name='root'),
    # 위랑 결과는 똑같지만 장고는 아래방식을 더 선호
    path('', RedirectView.as_view(pattern_name='instagram:post_list'), name='root'),

    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls')),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

# settings.MEDIA_URL
# settings.MEDIA_ROOT

blog1/urls.py
from django.urls import path

from blog1.views import post_list

app_name = 'blog1' # URL Reverse namespace 역할 하게 됨

urlpatterns = [
    path('', post_list, name='post_list'),
]

accounts/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import resolve_url


class Profile(models.Model):

    # foreignkey (unique=true) 와 유사하지만, reverse 차이!
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=6)

    # def get_absolute_url(self):
    #     # return reverse('instagram:post_detail', args=[self.pk])
    #     return resolve_url('accounts:profile', self.pk)

accounts/forms.py
import random
import time

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.core.exceptions import ValidationError

from accounts.models import Profile

User = get_user_model()

class LoginForm(AuthenticationForm):
    random.seed(int(time.time()))
    a = random.randrange(1, 10)
    b = random.randrange(1, 10)
    answer = forms.IntegerField(help_text=f'{a} + {b} = ?')

    ans = int(a) + int(b)
    def clean_answer(self):
        answer = self.cleaned_data.get('answer')
        if answer != self.ans:
            raise forms.ValidationError('땡~!')


        return answer




class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['address', 'zipcode']

# class PasswordChangeForm(forms.ModelForm):
#     pass

class PasswordChangingForm(PasswordChangeForm):

    old_password = forms.CharField(label="현재 비밀번호", widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '현재 비밀번호'}))
    new_password1 = forms.CharField(label="새 비밀번호", widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '새 비밀번호'}))
    new_password2 = forms.CharField(label="새 비밀번호 확인", widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'placeholder': '새 비밀번호 확인'}))

    def clean_new_password1(self):
        old_password = self.cleaned_data.get('old_password')
        new_password1 = self.cleaned_data.get('new_password1')

        if old_password and new_password1:
            if old_password == new_password1:
                raise ValidationError("새로운 암호는 기존 암호와 다르게 입력해주세요.")
        return new_password1

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

accounts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model, login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, UpdateView, CreateView

# @login_required
# def profile(request):
#     return render(request, 'accounts/profile.html')
from accounts.forms import ProfileForm, PasswordChangingForm
from accounts.models import Profile

User = get_user_model()

class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangingForm
    success_url = reverse_lazy('accounts:profile')


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

profile = ProfileView.as_view()

class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm

# profile_edit = ProfileUpdateView.as_view()

@login_required
def profile_edit(request):
    try:
        profile = request.user.profile

    except Profile.DoesNotExist:
        profile = None

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()

            return redirect(reverse('accounts:profile'))
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'accounts/profile_form.html', {
        'form': form,
    })

class SignupView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('instagram:post_list')
    template_name = 'accounts/signup_form.html'

    # def form_valid(self, form):
    #
    #     if self.request.method == "POST":
    #         #
    #         form = ProfileForm(self.request.POST, instance = get_user_model())
    #         if form.is_valid():
    #             profile = form.save(commit=False)
    #             profile.user = self.request.user
    #             profile.save()


signup = SignupView.as_view()

# signup = CreateView.as_view(
#     model=User,
#     form_class=UserCreationForm,
#     success_url=reverse_lazy('instagram:post_list'),
#     template_name='accounts/signup_form.html'
# )



# def signup(request):
#     pass

# def logout(request):
#     pass

accounts/templates/accounts/change-password.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="mb-5">
        <h1>비밀번호변경</h1>
    </div>
    <hr>
    <div class="form-group">
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3 col-3">
                {{ form.old_password.label }}
                {{ form.old_password }}
                {% if form.errors %}
                    {{ form.old_password.errors }}
                {% endif %}
            </div>

            <div class="mb-3 col-3">
                {{ form.new_password1.label }}
                {{ form.new_password1 }}
                {% if form.errors %}
                    {{ form.new_password1.errors }}
                {% endif %}
            </div>

            <div class="mb-3 col-3">
                {{ form.new_password2.label }}
                {{ form.new_password2 }}
                {% if form.errors %}
                    {{ form.new_password2.errors }}
                {% endif %}
            </div>

{#            {% bootstrap_form form %}#}
{#            {% for f in form.as_table %}#}
{#                {{ f }}#}
{#            {% endfor %}#}
            <input type="submit" value="확인" class="btn btn-primary col-1 mt-3">
        </form>

    </div>

{% endblock %}

accounts/templates/accounts/layout.html
{% extends 'layout.html' %}

accounts/templates/accounts/login_form.html
{% extends 'accounts/layout.html' %}
{% load bootstrap4 %}

{% block content %}
    {% if not user.is_authenticated %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
    {#        <table>#}
    {#            {{ form }}#}
    {#        </table>#}
            <input type="submit" value="Login" class="btn btn-primary mt-2"/>
        </form>
    </div>

    {% endif %}

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'accounts/layout.html' %}

{% block content %}
    <h2>User : {{ user }}</h2>

{#    {{ user.is_authenticated }}#}

    {% if user.profile %}
        <ul>
            <li>{{ user.profile.address }}</li>
            <li>{{ user.profile.zipcode }}</li>
        </ul>

    {% endif %}


    <div>
        <a href="{% url "accounts:profile_edit" %}" class="btn btn-primary">
            프로필 수정
        </a>

        <a href="{% url "accounts:password" %}" class="btn btn-secondary">
            비밀번호 변경
        </a>
    </div>



{% endblock %}

accounts/templates/accounts/profile_form.html
{% extends 'accounts/layout.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button class="btn btn-primary">프로필 수정</button>
            {% endbuttons %}
{#            <input type="button" value="프로필 수정" class="btn btn-primary mt-2"/>#}
        </form>
    </div>



{% endblock content %}

accounts/templates/accounts/signup_form.html
{% extends 'accounts/layout.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button class="btn btn-primary">회원 가입</button>
            {% endbuttons %}
{#            <input type="button" value="프로필 수정" class="btn btn-primary mt-2"/>#}
        </form>
    </div>



{% endblock content %}