askcompany/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# 아래 두개처럼 쓰면 안됨
# from django.conf import global_settings
# from askcompany import settings
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='root.html'), name='root'),

    # path('', RedirectView.as_view(url='/instagram/'), name='root'),
    # 위랑 결과는 똑같지만 장고는 아래방식을 더 선호
    path('', RedirectView.as_view(pattern_name='instagram:post_list'), name='root'),

    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls')),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

# settings.MEDIA_URL
# settings.MEDIA_ROOT

blog1/urls.py
from django.urls import path

from blog1.views import post_list

app_name = 'blog1' # URL Reverse namespace 역할 하게 됨

urlpatterns = [
    path('', post_list, name='post_list'),
]

instagram/urls.py
from django.urls import path, re_path, register_converter

from instagram.converters import YearConverter, MonthConverter, DayConverter
from instagram.views import post_list, post_detail, post_archive, post_archive_year, post_new, post_edit, post_delete, \
    response_csv

# from instagram.views import archives_year

app_name = 'instagram' # URL Reverse namespace 역할 하게 됨


register_converter(YearConverter, 'year')
register_converter(MonthConverter, 'month')
register_converter(DayConverter, 'day')

# Post.objects.all().values_list('create_at')
# Post.objects.all().values_list('create_at__year')
# Post.objects.all().values_list('create_at__year', flat=True)

urlpatterns = [
    path('new/', post_new, name='post_new'),
    path('<int:pk>/edit/', post_edit, name='post_edit'),
    path('<int:pk>/delete/', post_delete, name='post_delete'),

    path('', post_list, name='post_list'),
    path('<int:pk>', post_detail, name='post_detail'),

    # re_path(r'archives/(?P<year>\d+)/', archives_year),

    # 숫자 4개만 입력받음
    # re_path(r'archives/(?P<year>\d{4})/', archives_year),

    # 20으로 시작하는 숫자 4개만 입력받음
    # re_path(r'archives/(?P<year>20\d{2})/', archives_year),

    path('archive/', post_archive, name='post_archive'),
    path('archive/<year:year>/', post_archive_year, name='post_archive_year'),
    path('pandas/', response_csv, name='pandas'),
    # path('archive/<year:year>/<month:month>/', post_archive_month, name='post_archive_month'),
    # path('archive/<year:year>/<month:month>/<day:Day>', post_archive_day, name='post_archive_day'),

    # 첫번째 year는 converter이름이고 두번째 year는 전달할 인자
    # path('archives/<year:year>/', archives_year),



]

instagram/models.py
from datetime import timedelta, datetime

from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models
import pytz

# Create your models here.

# min_length_validator = MinLengthValidator()
# min_length_validator("hello")
from django.shortcuts import resolve_url
from django.urls import reverse
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(validators=[MinLengthValidator(5)])
    # upload_to 는 미디어파일저장되는 경로를바꾼다 media다 저장되면 찾기 힘듬으로...


    # 차량번호
    car_number = models.CharField(max_length=13, blank=True)
    # 운수사명
    fran_name = models.CharField(max_length=10, blank=True)

    # A/S 리스트 Boolean
    as_1 = models.BooleanField(default=False, verbose_name='A/S 목록 1')
    as_2 = models.BooleanField(default=False, verbose_name='A/S 목록 2')
    as_3 = models.BooleanField(default=False, verbose_name='A/S 목록 3')

    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y%m%d')

    tag_set = models.ManyToManyField('Tag', blank=True)
    is_public = models.BooleanField(default=False, verbose_name='공개여부', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Detail뷰가 구현이 되었다면 무조건 모델클래스에 get_absolute_url메소드를 구현하자!!!!!!!!!!

    @property
    def sum_as(self):
        count = 0
        if self.as_1:
            count += 1
        if self.as_2:
            count += 1
        if self.as_3:
            count += 1

        return count

    # - timedelta(seconds=86400)

    def created_yesterday(self):
        return self.created_at - timedelta(seconds=86400)

    @property
    def check_oneday(self):
        local_tz = pytz.timezone('Asia/Seoul')
        utc = pytz.UTC

        # created_at = self.created_at.replace(tzinfo=pytz.utc).astimezone(local_tz).timestamp()
        created_at = self.created_at.replace(tzinfo=pytz.utc).astimezone(local_tz)

        # yesterday = (datetime.today() - timedelta(days=1.2)).replace(tzinfo=pytz.utc).timestamp()
        yesterday = (timezone.now() - timedelta(days=1)).replace(tzinfo=pytz.utc).astimezone(local_tz)

        # print(yesterday)
        # print(created_at)

        # created_at_date = self.created_at.replace(tzinfo=pytz.utc).astimezone(local_tz)
        # yesterday_date = (datetime.today() - timedelta(days=1.5)).replace(tzinfo=pytz.utc)

        # print(created_yesterday.replace(tzinfo=pytz.utc).astimezone(local_tz))
        # print(created_yesterday.replace(tzinfo=None))
        # print(yesterday.replace(tzinfo=None))

        # print(created_at_date)
        # print(yesterday_date)

        # print(created_at)
        # print(yesterday)

        if(created_at > yesterday):
            return True
        else:
            return False

        # return self.created_at - timedelta(seconds=86400)

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        # return reverse('instagram:post_detail', args=[self.pk])
        return resolve_url('instagram:post_detail', self.pk)

    class Meta:
        ordering = ['-updated_at']

    def message_length(self):
        return len(self.message)



    # message_length 메소드에 이름부여
    message_length.short_description = "메세지 글자수"

class Comment(models.Model):

    # 위에 둘다 어느것이든지 동일한 결과임!
    # post = models.ForeignKey('instagram.Post', on_delete=models.CASCADE)
    # post = models.ForeignKey('Post', on_delete=models.CASCADE)

    # limit_choices_to 를 true로 하면 is_public에서 true인값만 나옴!
    post = models.ForeignKey(Post, on_delete=models.CASCADE) # post_id 필드가 생성된다.
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if(self.message):
            return self.message

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class PostImage(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='instagram/post/%Y%m%d', blank=True, null=True)

    # def __str__(self):
    #     return self.post.message

instagram/views.py
from datetime import datetime, timedelta
from urllib.parse import quote


import pandas as pd
from io import StringIO

from django.forms import modelformset_factory, inlineformset_factory
from django.http import HttpResponse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, CreateView, UpdateView, \
    DeleteView

from instagram.decorator import post_ownership_required, post_delete_ownership_required
from instagram.forms import PostForm, NotClearableFileInput, PostNonImageForm
from instagram.models import Post, PostImage


# post_list = login_required(ListView.as_view(model=Post, paginate_by=1))

# @method_decorator(login_required, name='dispatch')

# @login_required
# def post_delete(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#
#     if post.author != request.user:
#         messages.error(request, '작성자만 삭제할 수 있습니다.')
#         return redirect(post)
#
#     if request.method == 'POST':
#         post.delete()
#         messages.success(request, '포스팅을 삭제했습니다.')
#         return redirect('instagram:post_list')
#     return render(request, 'instagram/post_confirm_delete.html',{
#         'post': post,
#     })

@method_decorator(post_delete_ownership_required, 'get')
@method_decorator(post_delete_ownership_required, 'post')
class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    # success_url = reverse_lazy('instagram:post_list')

    def get_success_url(self):
        return reverse('instagram:post_list')


post_delete = PostDeleteView.as_view()


# @method_decorator(post_ownership_required, 'get')
class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 10



    def get_queryset(self):
        #created_at__gte = timezone.now() - datetime.timedelta(days=1)
        # qs = super().get_queryset().filter(author=self.request.user, created_at__gte = timezone.now() - timedelta(days=1))

        qs = super().get_queryset().filter(author=self.request.user)

        q = self.request.GET.get('q', '')
        if q:
            qs = qs.filter(message__icontains=q)
        return qs

post_list = PostListView.as_view()

@login_required
def post_new(request):

    if request.method == "POST":
        # post = Post()
        form = PostForm(request.POST, request.FILES)

        if form.is_valid(): # 유효성 검사가 수행됨!
            post = form.save(commit=False)

            post.author = request.user
            post.save()

            if(len(request.FILES.getlist('images')) > 10):
                messages.error(request, "이미지는 10개 이하로만 업로드가 가능합니다.")
                return redirect(reverse('instagram:post_new'))

            # get_absolute_url이 model에 적용 되어 있어야지만 아래 redirect가 반응한다.
            for img in request.FILES.getlist('images'):
                # Photo 객체를 하나 생성한다.
                photo = PostImage()
                # 외래키로 현재 생성한 Post의 기본키를 참조한다.
                photo.post = post
                # pictures로부터 가져온 이미지 파일들을 저장한다.
                photo.image = img
                # 데이터베이스에 저장
                photo.save()

            messages.success(request, '포스팅을 저장했습니다.')
            return redirect(post)
    else:
        form = PostForm()

    return render(request, 'instagram/post_form.html',{
        'form': form,
        'post': None,
    })

# @method_decorator(login_required, 'get')
# @method_decorator(login_required, 'post')
# class PostCreateView(CreateView):
#     model = Post
#     form_class = PostForm
#
#     # def post(self, request, *args, **kwargs):
#     #     files = request.FILES.getlist('imgs')
#     #     for img in files:
#     #         photo = PostImage()
#     #         photo.post = Post
#     #         photo.img = img
#     #         photo.save(())
#
#     def form_valid(self, form):
#         self.object = form.save(commit=False)
#         self.object.author = self.request.user
#         messages.success(self.request, '포스팅을 저장했습니다')
#         return super().form_valid(form)
#
#
# post_new = PostCreateView.as_view()

# updateview class를 함수형 뷰로 구현한것
@login_required
def post_edit(request, pk):

    post = get_object_or_404(Post, pk=pk)

    if post.author != request.user:
        messages.error(request, '작성자만 수정할 수 있습니다.')
        return redirect(post)

    ImgFormSet = inlineformset_factory(Post, PostImage, fields=('image', ), can_delete=True, extra=10, max_num=10, widgets={'image': NotClearableFileInput})
    if request.method == "POST":
        post_form = PostNonImageForm(request.POST, request.FILES, instance=post)
        form = ImgFormSet(request.POST, request.FILES, instance=post)
        # form_img = ImageForm(request.POST, request.FILES, instance=post_img)

        if form.is_valid() and post_form.is_valid():

            messages.success(request, '내역을 수정했습니다.')
            post_form.save()
            form.save()

            # get_absolute_url이 model에 적용 되어 있어야지만 아래 redirect가 반응한다.
            return redirect(post)
    else:
        form = ImgFormSet(instance=post)
        post_form = PostNonImageForm(instance=post)

    return render(request, 'instagram/post_formset.html', {
        'formset': form,
        'post': post,
        'post_form': post_form,
    })


@method_decorator(post_ownership_required, 'get')
@method_decorator(post_ownership_required, 'post')
class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get_queryset(self):
        # 로그인이 되어있지 않으면 공개된것만 봐라!
        # qs = super().get_queryset()
        qs = super().get_queryset().filter(author=self.request.user)
        # if not self.request == :
        #     qs = qs.filter(is_public=True)
        return qs


    def form_valid(self, form):
        # post = form.save()
        # for img in self.request.FILES.getlist('imgs'):
        #     # Photo 객체를 하나 생성한다.
        #     photo = PostImage()
        #     # 외래키로 현재 생성한 Post의 기본키를 참조한다.
        #     photo.post = post
        #     # imgs로부터 가져온 이미지 파일 하나를 저장한다.
        #     photo.image = img
        #     # 데이터베이스에 저장
        #     photo.save()
        messages.success(self.request, '포스팅을 수정했습니다.')
        return super().form_valid(form)


# post_edit = PostUpdateView.as_view()

# @login_required
# def post_list(request):
#     qs = Post.objects.all()
#     q = request.GET.get('q', '')
#     if q:
#         qs = qs.filter(message__icontains=q)
#
#     messages.info(request, 'messages 테스트')
#
#     # instagram/templates/instagram/post_list.html
#     return render(request, 'instagram/post_list.html', {
#         'post_list': qs,
#         'q': q,
#     })

# 클래스 기반뷰에 뷰 앞에다가 아래와 같이 적용하여 로그인 여부를 확인 후 실행!
class MyView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'



# def post_detail(request: HttpRequest, pk:int) -> HttpResponse:
#
#     post = get_object_or_404(Post, pk=pk)
#
#     # 위 코드가 아래 코드랑 동일 (페이지가 없는 pk에 대해서 not exist 에러를 띄움!
#     # try:
#     #     post = Post.objects.get(pk=pk)
#     # except Post.DoesNotExist:
#     #     raise Http404
#
#     return render(request, 'instagram/post_detail.html', {
#         'post': post,
#     })


# 위 함수형 코드랑 동일함!!
# post_detail = DetailView.as_view(
#     model=Post,
#     queryset=Post.objects.filter(is_public=True))

# @method_decorator(post_ownership_required, 'get')
class PostDetailView(DetailView):
    model = Post
    yesterday = datetime.today() - timedelta(seconds=86400)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["yesterday"] = self.yesterday
        return context

    def get_queryset(self):

        # qs = super().get_queryset().filter(author=self.request.user, created_at__gte=timezone.now() - timedelta(days=1))
        qs = super().get_queryset().filter(author=self.request.user)
        # if not self.request == :
        #     qs = qs.filter(is_public=True)
        return qs


post_detail = PostDetailView.as_view()

post_archive = ArchiveIndexView.as_view(model=Post, date_field='created_at', paginate_by=1)

post_archive_year = YearArchiveView.as_view(model=Post, date_field='created_at', make_object_list=True)

@login_required
def response_csv(request):
    df = pd.DataFrame([
        [100, 110, 120],
        [200, 210, 220],
        [300, 310, 320],
    ])
    encoded_filename = quote('pandas.csv')
    io = StringIO()
    df.to_csv(io)
    io.seek(0) # 끝에 있는 file cursor를 처음으로 이동
    response = HttpResponse(io, content_type='text/csv')
    response['Content-Disposition'] = "attachment; filename*=utf-8''{}".format(encoded_filename)
    return response


# def archives_year(request, year):
#
#     return HttpResponse(f'{year}년 archives')

instagram/templates/instagram/layout.html
{% extends 'layout.html' %}

instagram/templates/instagram/post_archive.html
<h2>latest</h2>

{{ latest }}

<h2>date_list</h2>

{#{{ date_list }}#}

{% for date in date_list %}
    {{ date.year }}
    {{ date|date:"Y" }}
{% endfor %}

instagram/templates/instagram/post_archive_year.html
<h2>year</h2>
{{ year }}

<h2></h2>
{{ previous_year }}

<h2></h2>
{{ next_year }}

<h2></h2>
{{ date_list }}

<h2></h2>
{{ object_list }}

instagram/templates/instagram/post_confirm_delete.html
{% extends 'instagram/layout.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}

        <div class="alert alert-danger">
            정말 삭제하시겠습니까?
        </div>

        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            내용보기
        </a>
        <input type="submit" value="삭제하겠습니다." class="btn btn-danger">
    </form>
{% endblock content %}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}
{% load tz %}
{% load sub_filter %}
{% load humanize %}
{% load display_fieldname %}


{% block title %}
    Post Detail pk#{{ post.pk }}
{% endblock title %}

{% block content %}

    <div class="card mb-4">

        <div class="card-header p-3">
            <h2>미터점 : {{ post.author }}</h2>
        </div>

        <div class="card-body">
            {{ post.message|linebreaks }}
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">A/S 목록</h4>
        </div>

        <div class="card-body">

            {% if post.as_1 %}
                <li style="list-style-type: circle;">as_1</li>
            {% endif %}
            {% if post.as_2 %}
                <li style="list-style-type: circle;">as_2</li>
            {% endif %}
            {% if post.as_3 %}
                <li style="list-style-type: circle;">as_3</li>
            {% endif %}

        </div>
    </div>

{#        <div>#}
{#             {{ post_form }}#}
{#        </div>#}

    <div class="card mt-4 mb-4">
        <div class="card-header">
            <h4 class="card-title">A/S 이미지</h4>
        </div>

        <div class="card-body">
            {% for photo in post.postimage_set.all%}
                <img src="{{photo.image.url}}" width="700"><br>
                <hr>
            {% endfor %}
        </div>

    </div>







{#    linebreaks를 넣어야 개행이 적용된다#}

{#    대상이 있으면 yesno로 표기해서 나타낼 수 있다.#}

{#    </div>#}
{##}
{#        {{ post.created_yesterday|date:"Y-m-d h:i:s" }}#}
{#    </div>#}
{#        {{ age|post.created_at }}#}
    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        목록
    </a>



    {% now "" as todays_date %}

    {% if post.check_oneday %}
        <a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-info">
            수정
        </a>
    {% endif %}

{#    {{ yesterday }}#}
    <a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">
        삭제
    </a>

{#    {{ post.created_at|timesince }}#}
{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends 'instagram/layout.html' %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
{#        {{ form.as_table }}#}
        {% bootstrap_form form %}
    </table>
    <input type="submit" value="저장" class="btn btn-primary"/>
    </form>
    <hr/>

    {% if post %}
        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            내용으로
        </a>
    {% endif %}

    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        목록
    </a>

{% endblock %}

instagram/templates/instagram/post_formset.html
{% extends 'instagram/layout.html' %}
{% load bootstrap4 %}

{% block content %}

    <form action="" method="post" enctype="multipart/form-data">
{#        {{ formset.non_form_errors.as_ul }}#}

        <div class="card mb-3">


            <div class="card-header">
                <h2 class="pb-3">이미지 업로드</h2>
            </div>

            <div class="card-body">
                <table>
                    {% csrf_token %}
                    {% for form in formset %}
                        {{ form.as_p }}
                        <hr>
                    {% endfor %}
                </table>

            </div>
            {{ formset.management_form }}
            {% for hidden in formset.hidden_fields %}
                {{ hidden }}
            {% endfor %}

        </div>


        <div class="card">
            <div class="card-header mt-2">
                <h2>
                    A/S 목록
                </h2>
                <h5 class="text-muted">
                    (A/S 받을 리스트에 체크)
                </h5>
            </div>

            <div class="card-body">
                <table>
                    {{ post_form }}
                </table>
{#                <div class="mb-2">#}
{#                    A/S 리스트1 :#}
{#                    <input type="checkbox" name="as_1" class="form-check-input" id="id_as_1">#}
{#                </div>#}
{#                <div class="mb-2">#}
{#                    A/S 리스트2 :#}
{#                    <input type="checkbox" name="as_2" class="form-check-input" id="id_as_2">#}
{#                </div>#}
{#                <div class="mb-2">#}
{#                    A/S 리스트3 :#}
{#                    <input type="checkbox" name="as_3" class="form-check-input" id="id_as_3">#}
{#                </div>#}
            </div>
        </div>

        <div class="mt-3">
            <input type="submit" value="저장" class="btn btn-primary"/>
        </div>

    </form>
    <hr/>

    {% if post %}
        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            내용으로
        </a>
    {% endif %}

    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        목록
    </a>

{% endblock %}

instagram/templates/instagram/post_list.html
{% extends 'instagram/layout.html' %}
{% load bootstrap4 %}

{% block title %}
    Instagram / Post List
{% endblock title %}

{% block content %}
    {#    action이 비워있으면 현재 폼이 있는경로#}
{#    <form action="" method="get">#}
{#        <div class="input-group col-lg-3 mb-2">#}
{#            <input class="form-control" name="q" value="{{ q }}">#}
{#            <input type="submit" class="btn btn-primary" value="검색">#}
{#        </div>#}
{##}
{#    </form>#}



    <table class="table table-bordered table-hover">
        <div class="mb-2">
            ※ 업로드 후 하루가 지나면 수정할 수 없습니다.
        </div>

        <thead class="table-secondary">

            <th>포스트 번호</th>
            <th>운수사</th>
            <th>미터점</th>
            <th>차량 번호</th>
            <th>A/S 목록 건수</th>
{#            <th>이미지</th>#}
            <th>메세지</th>
            <th>등록 날짜</th>
            <th>수정 날짜</th>

        </thead>

        <tbody>
            {% for post in post_list %}

                <tr>
                    <td>
                        {{ post.pk }}
                    </td>

                    <td>
                        {{ post.fran_name }}
                    </td>

                    <td>
                        {{ post.author }}
                    </td>

                    <td>
                        {{ post.car_number }}
                    </td>

                    <td>
                        {{ post.sum_as }}건
                    </td>

{#                    <td>#}
{#                        {% if post.photo %}#}
{#                            <img src="{{ post.photo.url }}" alt="" style="width: 300px;">#}
{#                        {% else %}#}
{#                                No Photo#}
{#                        {% endif %}#}
{##}
{#                    </td>#}

                    <td>
    {#                    <a href="{% url 'instagram:post_detail' post.pk %}">#}
                        <div style="max-width: 250px;">
                            <a href="{{ post.get_absolute_url }}">
                                {{ post.message }}
                            </a>
                        </div>
    {#                    </a>#}
                    </td>
                    <td>
                        {{ post.created_at }}
                    </td>

                    <td>
                        {{ post.updated_at }}
                    </td>

                </tr>
            {% endfor %}

        </tbody>
    </table>
    <a href="{% url 'instagram:post_new' %}" class="btn btn-primary btn-block col-sm-2 mt-3 mb-3">새 포스팅</a>
    {{ page.obj }}
    {% if is_paginated %}
        {% bootstrap_pagination page_obj size="small" justify_content="center" %}
    {% endif %}
{#    {{ is_paginated }}#}

{% endblock content %}