accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from accounts.forms import LoginForm
from accounts.views import profile, profile_edit, signup, PasswordsChangeView

app_name = 'accounts'

# app_name을 넣으면 무조건 reserve('accounts:profile')이런식으로 url을 만들어야한다
# url 'profile'이렇게 쓰고 싶으면 app_name이 없고 name만 설정해야한다!

urlpatterns = [
    # 로그인 되어있는데 로그인페이지로 임의로 들어가면 redirect_authenticated_user =True로 해준다, 그리고 setting가서 설정!
    path('login/', LoginView.as_view(template_name='accounts/login_form.html', form_class=LoginForm, redirect_authenticated_user =True), name='login'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', profile_edit, name='profile_edit'),
    # path('profile/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/change-password.html', success_url=reverse_lazy('accounts:profile')), name='password'),
    # path('profile/update/', account_update, name='account_update'),
    path('profile/password/', PasswordsChangeView.as_view(template_name='accounts/change-password.html'), name='password'),
    path('signup/', signup, name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

askcompany/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# 아래 두개처럼 쓰면 안됨
# from django.conf import global_settings
# from askcompany import settings
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='root.html'), name='root'),

    # path('', RedirectView.as_view(url='/instagram/'), name='root'),
    # 위랑 결과는 똑같지만 장고는 아래방식을 더 선호
    path('', RedirectView.as_view(pattern_name='instagram:post_list'), name='root'),

    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls')),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

# settings.MEDIA_URL
# settings.MEDIA_ROOT

blog1/urls.py
from django.urls import path

from blog1.views import post_list

app_name = 'blog1' # URL Reverse namespace 역할 하게 됨

urlpatterns = [
    path('', post_list, name='post_list'),
]

templates/layout.html
{% load bootstrap4 static %}
{% load i18n bootstrap4 %}
{#{% bootstrap_messages %}#}
<!doctype html>
<html lang="ko">
<head>

   <!-- CSS only -->
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/darkly/bootstrap.min.css" integrity="sha384-nNK9n28pDUDDgIiIqZ/MiyO3F4/9vsMtReZK39klb/MtkZI3/LtjSjlmyVPS3KdN" crossorigin="anonymous">#}
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">#}
{#    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>#}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.css' %}">
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'bootstrap-5.1.3-dist/js/bootstrap.js' %}"></script>

{#    구글폰트#}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+P+One&family=Nanum+Gothic&family=Nanum+Gothic+Coding&display=swap" rel="stylesheet">

    <style>
        body{
            {#padding-top: 5rem;#}
            padding-bottom: 2rem;
        }
    </style>
</head>

{#body태그가 있어야 debug-toolbar가 보인다#}
{# style="'Nanum Gothic Coding', monospace;"#}
<body style="font-family:'Nanum Gothic', sans-serif;">

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'instagram:post_list' %}">KMSolution</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'instagram:post_list' %}">Home</a>
                    </li>
                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}?next={% url 'instagram:post_list' %}">로그인</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:profile' %}">프로필</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}?next={% url 'instagram:post_list' %}">로그아웃</a>
                        </li>
                    {% endif %}

                </ul>
                <form class="d-flex">
                    <input class="form-control" name="q" type="search" placeholder="Search" aria-label="Search" value="{{ q }}">
                    <button class="btn btn-outline-success mx-3" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">

{#                    {% bootstrap_messages %}#}
               {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message.message }}
                              <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            </div>

                        {% endfor %}
                    </div>
                {% endif %}

                    {% block content %}

                    {% endblock content %}

            <hr/>
            &copy; KMS Company.
            </div>

        </div>
    </div>


</body>
</html>



{#{{ post_list }}#}

templates/root.html
Instagram with Django/React.